### ISSUE TITLE
回复太频繁容易被吞

### ISSUE THREAD

**Issue by oplaaa** [eggggi/pcr_scrimmage#13]
由于这个问题跟角色什么的不是很相关所以单独开一个Issue了，目前经常在大群中发现bot发的消息被tx吞了，或者卡住发不出来的情况，怀疑是因为一下子发好几条消息的原因（例如扔骰子命令后，行走的回复，踩到格子的回复，需要使用技能的回复，回复地图全部是同时发送的），这方面如果给bot每次回复东西后给一个延时1s或更多时间再回复是否会更好些呢？

**Comment by eggggi** [comment]
其实不是回复的时间间隔问题，一般这种情况是你机器人的qq账号被风控，会有概率发不出消息，如果你用的是gocqhttp，gocqhttp的日志上会有提示的。
回复延迟是有的，发送间隔太短可能会导致顺序不对，我手动加的1s延迟，代码里也是能看到的。
关于风控，可能是因为你这个账号平时不太活跃，然后一下子突然非常活跃导致。也有可能是被举报了。

**Comment by oplaaa** [comment]
风控的情况知道，使用的是CQHTTP，并没有风控提示，后台提示消息已经成功发出了，实际群里并没出现，这个bot我一直在使用的，用了一年多天天都比较活跃的那种（因为还有其他功能），那我也不是很清楚具体原因了，目前也就玩这个小游戏会出现这种情况，其他回复比较多的小游戏(例如隔壁的神经衰弱之类的)没出现过

**Comment by eggggi** [comment]
消息被吞gocqhttp还没有提示，这种情况我也没见过\_(:з)∠)\_
可以留意下报错什么的，或者更新下gocqhttp。。
会不会是网络问题呢。。

**Comment by oplaaa** [comment]
测试半天终于又遇到一次被吞情况了，看到的报错如下

[2021-09-23 17:59:19,861 pcr_scrimmage] INFO: Message 1456797247 triggered throw_dice by PrefixTrigger.
[2021-09-23 17:59:40,616 pcr_scrimmage] ERROR: <class 'aiocqhttp.exceptions.ActionFailed'> occured when throw_dice handling message 1456797247.
[2021-09-23 17:59:40,616 pcr_scrimmage] ERROR: <ActionFailed, retcode=100>
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\msghandler.py", line 28, in handle_message
    await sf.func(bot, event)
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\service.py", line 217, in wrapper
    return await func(bot, event)
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\pcr_scrimmage\pcr_scrimmage.py", line 1173, in throw_dice
    await bot.send(ev, image.cqcode)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\__init__.py", line 251, in send
    return await self.send_msg(**params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\__init__.py", line 219, in call_action
    return await self._api.call_action(action=action, **params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 186, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 161, in call_action
    return _handle_api_result(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 51, in _handle_api_result
    raise ActionFailed(retcode=result.get('retcode'))
aiocqhttp.exceptions.ActionFailed: <ActionFailed, retcode=100>

**Comment by eggggi** [comment]
retcode=100这个问题太泛了，很难判断具体原因。有可能是网络问题，也有可能是资源问题。我看这里是发送图片的时候的报错，尝试换一下发送图片的协议试试？或者更新下aiocqhttp和gocqhttp？
再或者可以在

	img.save(image.path)
	await bot.send(ev, image.cqcode)

中间加一行

	img.save(image.path)
	await asyncio.sleep(PROCESS_WAIT_TIME)
	await bot.send(ev, image.cqcode)

感觉也有可能是因为性能问题导致图片未完全保存成功就尝试读取导致

**Comment by oplaaa** [comment]
这几天生病了没来得及修改测试，今天终于好点了（能上班了）后立刻修改测试了一下，整体出现消息被吞的几率大大减少了，除非有人在bot还未回复的时候就发出命令会导致bot混乱以外好太多了，感谢
顺便提供下新写的人物~

	1057:{
		"name":"吉塔",
		"health":900,
		"distance":5,
		"attack":90,
		"defensive":60,
		"tp":0,

		"active_skills": [
			{
				"name":"星河一天",
				"text":"对最近的目标造成150(+1.5攻击力)伤害,并提升自身150攻击力持续1回合",
				"tp_cost":100,
				"trigger":TRIGGER_NEAR,
				"passive":[0],
				"effect":{
					EFFECT_HURT:(150, Attr.ATTACK, 0, 1.5, False),
				}
			},
			{
				"name":"广域斩击",
				"text":"对目标造80(+1.0攻击力)伤害,恢复自身30TP",
				"tp_cost":0,
				"trigger":TRIGGER_SELECT_EXCEPT_ME,
				"passive":[1],
				"effect":{
					EFFECT_HURT:(80, Attr.ATTACK, 0, 1.0, False),
				}
			},
			{
				"name":"剑意迸发",
				"text":"恢复自身30TP",
				"tp_cost":0,
				"trigger":TRIGGER_ME,
				"passive":[],
				"effect":{
					EFFECT_ATTR_CHANGE:[(Attr.TP, 30, 0, 0)],
				}
			}
		],
		
		"passive_skills": [
			{
				"trigger":TRIGGER_ME,
				"effect":{
					EFFECT_BUFF:(BuffType.NormalAttrAtkUp, 150, 1),
				}
			},
			{
				"trigger":TRIGGER_ME,
				"effect":{
					EFFECT_ATTR_CHANGE:[(Attr.TP, 30, 0, 0)],
				}
			}
		]
	},
	1049:{
		"name":"静流",
		"health":1200,
		"distance":5,
		"attack":70,
		"defensive":120,
		"tp":0,

		"active_skills":[
			{
				"name":"神圣超越",
				"text":"对目标造成100(+1.5防御力)的伤害，提升自身80点防御，为自己增添一个可抵御300点伤害的护盾(一次)",
				"tp_cost":80,
				"trigger":TRIGGER_SELECT_EXCEPT_ME,
				"passive":[0],
				
				"effect":{
					EFFECT_HURT:(100, Attr.DEFENSIVE, 0, 1.5, False),
				}
			},
			{
				"name":"圣灵愈合",
				"text":"恢复目标100(+1.5防御力)的生命值，提升目标50点防御力",
				"tp_cost":40,
				"trigger":TRIGGER_SELECT,
				"passive":[],
				
				"effect":{
					EFFECT_ATTR_CHANGE:[
						(Attr.NOW_HEALTH, 100, Attr.DEFENSIVE, 1.5),
						(Attr.DEFENSIVE, 50, 0, 0),],
				}
			},
			{
				"name":"守护",
				"text":"为目标提供一个可抵御200点伤害的护盾，可触发1次",
				"tp_cost":30,
				"trigger":TRIGGER_SELECT,
				"passive":[],
				
				"effect":{
					EFFECT_BUFF:(BuffType.Shield, 200, 1),
				}
			}
		],
		"passive_skills":[
			{
				"trigger":TRIGGER_ME,
				"effect":{
					EFFECT_ATTR_CHANGE:[(Attr.DEFENSIVE, 80, 0, 0),],
					EFFECT_BUFF:(BuffType.Shield, 300, 1),
				},
			}
		]
	},
